// Shared table styles for all pages
export const tableStyles = {
  container: {
    fontFamily: "'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif",
    padding: '30px',
    backgroundColor: '#f8f9fa',
    minHeight: '100vh',
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '20px',
  },
  heading: {
    color: '#343a40',
    fontSize: '1.8rem',
    margin: 0,
  },
  breadcrumb: {
    fontSize: '14px',
    color: '#6c757d',
    marginBottom: '15px',
  },
  breadcrumbLink: {
    color: '#007bff',
    textDecoration: 'none',
    cursor: 'pointer',
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse',
    backgroundColor: '#fff',
    borderRadius: '8px',
    overflow: 'hidden',
    boxShadow: '0 4px 12px rgba(0, 0, 0, 0.05)',
  },
  th: {
    backgroundColor: '#343a40',
    color: '#fff',
    padding: '12px 15px',
    textAlign: 'left',
    fontWeight: '600',
    fontSize: '14px',
  },
  td: {
    padding: '12px 15px',
    borderBottom: '1px solid #e9ecef',
    fontSize: '14px',
    color: '#495057',
  },
  tr: {
    transition: 'background-color 0.2s',
  },
  trHover: {
    backgroundColor: '#f8f9fa',
  },
  clickableCell: {
    color: '#007bff',
    cursor: 'pointer',
    fontWeight: '500',
  },
  badge: {
    padding: '4px 8px',
    borderRadius: '4px',
    fontSize: '12px',
    fontWeight: '600',
  },
  badgeStandalone: {
    backgroundColor: '#e9f5ff',
    color: '#007bff',
  },
  badgeModuleBased: {
    backgroundColor: '#fff3cd',
    color: '#664d03',
  },
  button: {
    padding: '6px 12px',
    borderRadius: '4px',
    border: 'none',
    cursor: 'pointer',
    fontWeight: '500',
    fontSize: '12px',
    marginRight: '5px',
  },
  viewButton: {
    backgroundColor: '#17a2b8',
    color: 'white',
  },
  editButton: {
    backgroundColor: '#ffc107',
    color: '#343a40',
  },
  deleteButton: {
    backgroundColor: '#dc3545',
    color: 'white',
  },
  addButton: {
    backgroundColor: '#28a745',
    color: 'white',
    padding: '10px 20px',
    fontSize: '14px',
  },
  backButton: {
    backgroundColor: '#6c757d',
    color: 'white',
    padding: '8px 16px',
    fontSize: '14px',
    marginRight: '10px',
  },
  // Form styles for edit/add pages
  formContainer: {
    backgroundColor: '#fff',
    padding: '30px',
    borderRadius: '8px',
    boxShadow: '0 4px 12px rgba(0, 0, 0, 0.05)',
    maxWidth: '600px',
  },
  formGroup: {
    marginBottom: '20px',
  },
  label: {
    display: 'block',
    marginBottom: '8px',
    fontWeight: '600',
    color: '#343a40',
    fontSize: '14px',
  },
  input: {
    width: '100%',
    padding: '10px 12px',
    borderRadius: '4px',
    border: '1px solid #ced4da',
    fontSize: '14px',
    boxSizing: 'border-box',
  },
  select: {
    width: '100%',
    padding: '10px 12px',
    borderRadius: '4px',
    border: '1px solid #ced4da',
    fontSize: '14px',
    backgroundColor: '#fff',
    boxSizing: 'border-box',
  },
  textarea: {
    width: '100%',
    padding: '10px 12px',
    borderRadius: '4px',
    border: '1px solid #ced4da',
    fontSize: '14px',
    resize: 'vertical',
    boxSizing: 'border-box',
    minHeight: '100px',
  },
  submitButton: {
    backgroundColor: '#007bff',
    color: 'white',
    padding: '10px 20px',
    fontSize: '14px',
  },
  cancelButton: {
    backgroundColor: '#6c757d',
    color: 'white',
    padding: '10px 20px',
    fontSize: '14px',
    marginLeft: '10px',
  },
  warningBox: {
    backgroundColor: '#fff3cd',
    border: '1px solid #ffc107',
    borderRadius: '4px',
    padding: '15px',
    marginBottom: '20px',
    color: '#856404',
  },
  emptyState: {
    textAlign: 'center',
    padding: '40px',
    color: '#6c757d',
    fontStyle: 'italic',
  },
};
